### ISSUE TITLE
Dear author！！

### ISSUE THREAD

**Issue by Jinn02-25** [zhengwang100/RECT#3]
Hello author, my research direction is also to do GNN, and I am currently looking at the research on class imbalance node classification. I want to run the RECT model. Can you send me the version number of the RECT environment?

**Comment by zhengwang100** [comment]
Might be Pytorch 1.0

**Comment by Jinn02-25** [comment]
Ok thanks, I'm also using 1.0.
What version of PYG are you using? Could you please put the dependencies of your conda environment?
